name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, fileinfo
        coverage: none
        
    - name: Copy .env
      run: php -r "file_exists('.env') || file_put_contents('.env', file_get_contents('.env.example'));"
        
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        npm install
        npm install -D tailwindcss postcss autoprefixer
        
    - name: Generate key
      run: php artisan key:generate
        
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
        
    - name: Build assets
      run: |
        npm run build
        
    - name: Optimize Laravel
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        publish_branch: gh-pages
        commit_message: ${{ github.event.head_commit.message }} 